name: Run Flexiroam Script Every 12 Hours

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Or specify your Python version (e.g., 3.9, 3.10)

      - name: Create virtual environment
        run: python3 -m venv .venv  # Or python -m venv .venv

      - name: Activate virtual environment
        run: |
          source .venv/bin/activate  # Linux/macOS
          # .venv\Scripts\activate  # Windows (if needed)

      - name: Install dependencies
        run: pip install -r requirements.txt  # Installs in the virtual environment

      - name: Run Flexiroam script
        run: python Flexiroam_FreePlan.py
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
